apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  destination:
    server: kind-local-cluster-argocd
    namespace: argocd
  source:
    repoURL: https://github.com/niki-playground/multi-app-argocd.git
    targetRevision: main
    path: apps
  syncPolicy:
    automated: {}
